config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'ror', to: 'portfolios#ror'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  #temporary catch all
  get '/*missing', to: 'pages#missing'
  
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies, dependent: :destroy
    accepts_nested_attributes_for :technologies, 
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    
    include Placeholder
    validates_presence_of :title, :body, :main_image, :thumb_image
    
    def self.by_position
        order("position ASC")
    end
    
    def self.ror
        where(subtitle: "Ruby on Rails")
    end
    
    scope :html, -> {where(subtitle: "HTML/CSS")}
    
    after_initialize :set_defaults
    
    def set_defaults
        self.main_image ||= Placeholder.image_generator(height:'600', width:'400')
        self.thumb_image ||= Placeholder.image_generator(height:'350', width:'200')
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
  layout "portfolio"
  access all: [:show, :index, :ror], user:{except: [:destroy, 
                                                    :new, 
                                                    :create, 
                                                    :update, 
                                                    :edit,
                                                    :sort
                                                    ]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.by_position
  end
  
  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    head :ok
  end
  
  def ror
    @ror_portfolio_items = Portfolio.ror
  end
  
  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end    
  
  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    respond_to do |format|
      if @portfolio_item.save
        format.html {redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html {render :new }
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html {redirect_to portfolios_path, notice: 'Your portfolio item has been updated.' }
      else
        format.html {render :edit }
      end
    end
  end
  
  def show
  end    
  
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio item was removed.' }
    end
  end  
  
  private 
  
  def portfolio_params
    params.require(:portfolio).permit(:title, 
                                      :subtitle, 
                                      :body,
                                      technologies_attributes: [:name]
                                     )
  end
  
  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class:"form-control" %>
    </div> 
    
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_field :body, class:"form-control" %>
    </div>
    
    <ul>
        <%= f.fields_for :technologies  do |technology_form| %>
            <li>
                <%= technology_form.label :name %>
                <%= technology_form.text_field :name, class:"form-control" %>

            </li>
        <% end %>
    </ul>

    <div class="action form-group">
        <%= f.submit class: "btn btn-primary" %>
    </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <p class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio_form">
<h1>Edit this portfolio item:</h1>

<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= 'sortable' if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio_form">

        <h1>Create a new portfolio item:</h1>
        <%= render 'form', portfolio_item: @portfolio_item %>

</div>

app/views/portfolios/ror.html.erb
<h1>Ruby on Rails Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @ror_portfolio_items.each do |portfolio_item| %>
    <h2><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item)%></h2>
    <h3><%= portfolio_item.subtitle %></h3>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <br>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
    <%= link_to "Delete Portfolio item", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure?" } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <%= image_tag @portfolio_item.main_image %>
        </div>
        <div class="col-md-5">
            <h2><%= @portfolio_item.title %></h2>
            <hr>
            <h3><%= @portfolio_item.subtitle %></h3>
            <p><%= @portfolio_item.body %></p>
            <hr>
            <h3>Technologies Used</h3>
            <% @portfolio_item.technologies.each do |t| %>
                <p><%= t.name %></p>
            <% end %>
        </div>
    </div>
</div>